In [18]:
import tensorflow as tf
import numpy as np
import csv
import pandas as pd


In [81]:
iris = pd.read_csv("iris.csv")
iris = iris.sample(frac=1).reset_index(drop=True)
iris.head(n =10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0  126            7.2           3.2            6.0           1.8   
1   91            5.5           2.6            4.4           1.2   
2   44            5.0           3.5            1.6           0.6   
3  112            6.4           2.7            5.3           1.9   
4  142            6.9           3.1            5.1           2.3   
5   16            5.7           4.4            1.5           0.4   
6   52            6.4           3.2            4.5           1.5   
7   89            5.6           3.0            4.1           1.3   
8   50            5.0           3.3            1.4           0.2   
9  136            7.7           3.0            6.1           2.3   

           Species  
0   Iris-virginica  
1  Iris-versicolor  
2      Iris-setosa  
3   Iris-virginica  
4   Iris-virginica  
5      Iris-setosa  
6  Iris-versicolor  
7  Iris-versicolor  
8      Iris-setosa  
9   Iris-virginica

In [82]:
x_train = np.zeros((120,4),dtype = float)
y_train = np.zeros(120, dtype= int)
x_test = np.zeros((30,4),dtype = float)
y_test = np.zeros(30, dtype= int)

In [89]:
for i in range(150):
    if i < 120:
        x_train[i][0] = iris.values[i][1]
        x_train[i][1] = iris.values[i][2]
        x_train[i][2] = iris.values[i][3]
        x_train[i][3] = iris.values[i][4]
        y_train[i] = check_species(iris.values[i][5])
    else:
        x_test[i-120][0] = iris.values[i][1]
        x_test[i-120][1] = iris.values[i][2]
        x_test[i-120][2] = iris.values[i][3]
        x_test[i-120][3] = iris.values[i][4]
        y_test[i-120] = check_species(iris.values[i][5])

In [83]:
def check_species(y):
    if y == 'Iris-virginica':
        return 0
    elif y == 'Iris-versicolor':
        return 1
    else:
        return 2

In [93]:
classes = ['Iris-virginica','Iris-versicolor','Iris-setosa']
x_train = tf.keras.utils.normalize(x_train, axis = 1) # normalizing from 0-255 to 0-1
x_test = tf.keras.utils.normalize(x_test, axis = 1)

In [128]:
x_test

array([[0.77530021, 0.28304611, 0.54147951, 0.15998258],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.86093857, 0.44003527, 0.24871559, 0.0573959 ],
       [0.76521855, 0.33391355, 0.52869645, 0.15304371],
       [0.76701103, 0.35063361, 0.51499312, 0.15340221],
       [0.70600618, 0.2383917 , 0.63265489, 0.21088496],
       [0.74143307, 0.29421947, 0.57667016, 0.17653168],
       [0.72712585, 0.26661281, 0.60593821, 0.18178146],
       [0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.71718148, 0.31640359, 0.58007326, 0.22148252],
       [0.77729093, 0.57915795, 0.24385598, 0.030482  ],
       [0.72415258, 0.32534391, 0.56672811, 0.22039426],
       [0.71562645, 0.3523084 , 0.56149152, 0.22019275],
       [0.79594782, 0.55370283, 0.24224499, 0.03460643],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.68914871, 0.33943145, 0.58629069, 0.25714504],
       [0.80597792, 0.52151512, 0.26865931, 0.07901744],
       [0.80327412, 0.55126656,

In [114]:
model = tf.keras.models.Sequential() 
model.add(tf.keras.layers.Flatten()) ## input layer flattening the multi-dimension x_train into a 1-d array
model.add(tf.keras.layers.Dense(125, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(125, activation = tf.nn.relu))
model.add(tf.keras.layers.Dense(3, activation = tf.nn.softmax))# o/p layer where nodes equal to number of classes
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy',metrics = ['accuracy']) 
                                        ## optimizer function, error measure and metrics
model.fit(x_train,y_train,epochs = 50)

Epoch 1/50
120/120 [==============================] - 1s 5ms/step - loss: 1.0996 - acc: 0.3917
Epoch 2/50
120/120 [==============================] - 0s 50us/step - loss: 1.0620 - acc: 0.6583
Epoch 3/50
120/120 [==============================] - 0s 56us/step - loss: 1.0322 - acc: 0.6750
Epoch 4/50
120/120 [==============================] - 0s 56us/step - loss: 1.0048 - acc: 0.6750
Epoch 5/50
120/120 [==============================] - 0s 60us/step - loss: 0.9763 - acc: 0.6750
Epoch 6/50
120/120 [==============================] - 0s 59us/step - loss: 0.9445 - acc: 0.6750
Epoch 7/50
120/120 [==============================] - 0s 54us/step - loss: 0.9090 - acc: 0.6750
Epoch 8/50
120/120 [==============================] - 0s 56us/step - loss: 0.8718 - acc: 0.6750
Epoch 9/50
120/120 [==============================] - 0s 48us/step - loss: 0.8335 - acc: 0.6750
Epoch 10/50
120/120 [==============================] - 0s 56us/step - loss: 0.7931 - acc: 0.6750
Epoch 11/50
120/120 [===================

In [115]:
val_loss, val_acc = model.evaluate(x_test, y_test)
print(val_loss, val_acc)

30/30 [==============================] - 0s 7ms/step
0.1971525102853775 0.9333333373069763


In [133]:
predictions = model.predict(x_test)
predictions[0]

array([0.40880692, 0.5859849 , 0.00520825], dtype=float32)

In [150]:
actual=[]
predicted=[]
for i in range(30):
    actual.append( classes[y_test[i]])
    predicted.append( classes[np.argmax(predictions[i])])

# predict = pd.DataFrame({'Actual Class' : actual, 'Predicted Class' : predicted})
    

In [153]:

predict = pd.DataFrame({'Actual Class' : actual, 'Predicted Class' : predicted})

In [154]:
predict

Actual Class  Predicted Class
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2       Iris-setosa      Iris-setosa
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5    Iris-virginica   Iris-virginica
6   Iris-versicolor   Iris-virginica
7    Iris-virginica   Iris-virginica
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10      Iris-setosa      Iris-setosa
11   Iris-virginica   Iris-virginica
12   Iris-virginica   Iris-virginica
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15   Iris-virginica   Iris-virginica
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18  Iris-versicolor  Iris-versicolor
19  Iris-versicolor  Iris-versicolor
20  Iris-versicolor  Iris-versicolor
21  Iris-versicolor   Iris-virginica
22  Iris-versicolor  Iris-versicolor
23  Iris-versicolor  Iris-versicolor
24   Iris-virginica   Iris-virginica
25  Iris-versicolor  Iris-versicolor
26      Iris-setosa      Iris-setosa
27      Iris-setosa      Iris-setosa
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa

In [152]:
predicted

['Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa']

In [139]:

x = np.random.randn(5)
y = np.sin(x)
df = pd.DataFrame({'x':x, 'y':y})

In [140]:
type(x)

numpy.ndarray

In [144]:
temp=np.ndarray(predicted)
# type(np.ndarray(predicted))
print(type(temp))

TypeError: 'str' object cannot be interpreted as an integer

In [149]:
predictions

array([[4.08806920e-01, 5.85984886e-01, 5.20825479e-03],
       [1.34888478e-06, 8.00106488e-03, 9.91997540e-01],
       [1.91063500e-05, 4.14106436e-02, 9.58570182e-01],
       [1.73929930e-01, 8.14852774e-01, 1.12173175e-02],
       [1.06169045e-01, 8.78861308e-01, 1.49695938e-02],
       [9.58853662e-01, 4.10407260e-02, 1.05596882e-04],
       [6.87438130e-01, 3.10704112e-01, 1.85780227e-03],
       [8.90230954e-01, 1.09354302e-01, 4.14776296e-04],
       [1.30850015e-06, 7.85462279e-03, 9.92144108e-01],
       [8.33573997e-01, 1.65677354e-01, 7.48659833e-04],
       [1.56131284e-06, 8.59001931e-03, 9.91408408e-01],
       [7.50770450e-01, 2.47891858e-01, 1.33776187e-03],
       [6.46960497e-01, 3.50752890e-01, 2.28660740e-03],
       [2.09422410e-06, 1.03495307e-02, 9.89648402e-01],
       [2.31477929e-06, 1.12397168e-02, 9.88757968e-01],
       [9.10930037e-01, 8.87508318e-02, 3.19096755e-04],
       [1.61042590e-05, 3.59831266e-02, 9.64000702e-01],
       [1.74844479e-06, 9.32278